apiVersion: v1
kind: Pod
metadata:
  name: test-db
spec:
  containers:
    - name: my-db-container
      image: mysql:latest
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: config-db
        - secretRef:
            name: secret-db
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
        - name: secrets-vol
          mountPath: /etc/secrets
  volumes:
    - name: config-vol
      configMap:
        name: config-db
    - name: secrets-vol
      secret:
        secretName: secret-db
